# Generated by Django 4.2 on 2023-04-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'auta',
            },
        ),
    ]
