# Generated by Django 4.2 on 2023-04-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auta_zdj_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auta',
            name='zdj_url',
            field=models.CharField(default='https://www.wyborkierowcow.pl/wp-content/uploads/2022/03/modele-audi-5-a4.jpg', max_length=255),
        ),
    ]
