# Generated by Django 4.2 on 2023-04-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_auta_zdj_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='auta',
            name='cena',
            field=models.IntegerField(default='666'),
        ),
    ]
