# Generated by Django 4.2 on 2023-04-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auta_cena'),
    ]

    operations = [
        migrations.AddField(
            model_name='auta',
            name='popularnosc',
            field=models.IntegerField(default='0'),
        ),
    ]
