# Generated by Django 4.2 on 2023-04-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='auta',
            name='moc',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='auta',
            name='paliwo',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='auta',
            name='spalanie',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='auta',
            name='typ',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
