# Generated by Django 4.2 on 2023-04-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auta_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auta',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
