# Generated by Django 4.2 on 2023-05-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_auta_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auta',
            name='zdj_url',
            field=models.CharField(default='https://media.istockphoto.com/id/1281739158/vector/car-vector-logo-fit-for-automotive-repair-transportation-or-car-shop-logo-flat-color-style.jpg?s=612x612&w=0&k=20&c=cuUSEnzQUQZ7sLfsoFmaKoMxLtCMMYVM2nh3QvhbEMc=', max_length=255),
        ),
    ]
