# Generated by Django 4.2 on 2023-05-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_auta_zdj_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutaSprzedane',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=255)),
                ('zdj_url', models.CharField(default='https://media.istockphoto.com/id/1281739158/vector/car-vector-logo-fit-for-automotive-repair-transportation-or-car-shop-logo-flat-color-style.jpg?s=612x612&w=0&k=20&c=cuUSEnzQUQZ7sLfsoFmaKoMxLtCMMYVM2nh3QvhbEMc=', max_length=255)),
                ('cena', models.IntegerField(default='666')),
                ('model', models.CharField(default='null', max_length=255)),
                ('popularnosc', models.IntegerField(default='0')),
                ('paliwo', models.CharField(default='null', max_length=255)),
                ('spalanie', models.FloatField(default=0.0)),
                ('typ', models.CharField(default='null', max_length=255)),
                ('moc', models.IntegerField(default='0')),
                ('uzytkownik', models.CharField(default='null', max_length=255)),
            ],
            options={
                'db_table': 'auta_sprzedane',
            },
        ),
    ]
